### ISSUE TITLE
Cannot install iconv via npm

### ISSUE THREAD

**Issue by nickast** [bnoordhuis/node-iconv#99]
Hello Ben,

I wanted to ask you if you can help me resolve the following problem.
I am running npm install iconv but I get the following stack trace:

npm http GET https://registry.npmjs.org/iconv
npm http 304 https://registry.npmjs.org/iconv
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan

> iconv@2.1.4 install /Users/username/Workspace/helloapp/node_modules/iconv
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

gyp: Error 1 running xcodebuild
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/username/Workspace/helloapp/node_modules/iconv
gyp ERR! node -v v0.10.24
gyp ERR! node-gyp -v v0.12.1
gyp ERR! not ok 
npm ERR! iconv@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iconv@2.1.4 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "iconv" "--save"
npm ERR! cwd /Users/nickast/Workspace/www/digitalcube.gr/cosend
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nickast/Workspace/www/digitalcube.gr/cosend/npm-debug.log
npm ERR! not ok code 0

**Comment by kiyanwang** [comment]
I'm not sure if this related, but as of last night we've been unable to install iconv, in our case we get the following error on Ubuntu 12.04:

```
gyp WARN install got an error, rolling back install
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Object 0.10.13 has no method 'slice'
gyp ERR! stack     at remove (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/remove.js:37:21)
gyp ERR! stack     at Object.self.commands.(anonymous function) [as remove] (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:66:37)
gyp ERR! stack     at Gunzip.cb (/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:33:20)
gyp ERR! stack     at Gunzip.EventEmitter.emit (events.js:117:20)
gyp ERR! stack     at Zlib._binding.onerror (zlib.js:298:10)
gyp ERR! System Linux 3.2.0-23-generic
gyp ERR! command "node" "/opt/node-v0.10.13-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /vagrant/talis/rl-app/node_modules/iconv
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Please file an Issue:
gyp ERR!     <https://github.com/TooTallNate/node-gyp/issues>
unbuild iconv@2.1.8
```

**Comment by asistent0** [comment]
i am also getting issues with installing iconv:

`$ npm install iconv -g

> iconv@2.2.0 install C:\Users\pc2\AppData\Roaming\npm\node_modules\iconv
> node-gyp rebuild


C:\Users\pc2\AppData\Roaming\npm\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\pc2\AppData\Roaming\npm\node_modules\iconv
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "iconv" "-g"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! iconv@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iconv
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\OpenServer\domains\nodejs.test\Lesson 3\npm-debug.log
`

**Comment by bnoordhuis** [comment]
@asistent0 It's in the error message:

> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

**Comment by Rachida-Djellal** [comment]
Hello Ben,

I wanted to ask you if you can help me resolve the following problem.
I am running npm install iconv but I get the following stack trace:

> leveldown@0.10.6 install C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\leveldown
> node-gyp rebuild


C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Users\djellal.rachida\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\djellal.rachida\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:937:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\djellal.rachida\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\leveldown
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok

> iconv@2.1.4 install C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\iconv
> node-gyp rebuild


C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Users\djellal.rachida\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\djellal.rachida\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:937:8)
gyp ERR! stack     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\djellal.rachida\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\iconv
gyp ERR! node -v v14.21.3
gyp ERR! node-gyp -v v5.1.1
gyp ERR! not ok
npm WARN miller-rabin@1.1.1 requires a peer of bn.js@^0.15.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package request-json is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@0.10.6 (node_modules\leveldown):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@0.10.6 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\djellal.rachida\AppData\Roaming\npm-cache\_logs\2024-02-28T10_14_31_284Z-debug.log 
i used windows

**Comment by bnoordhuis** [comment]
Hi @Rachida-Djellal, I can't say for sure but this:

>  gyp ERR! stack Error: self signed certificate in certificate chain

Suggests you may be behind some (corporate?) proxy. Check your npm config.

Your version of node, v14.21.3, is also pretty old so it's possible the built-in TLS certificate store is out of date. There's not really much you can do about that (it's baked in) except upgrade.

**Comment by Rachida-Djellal** [comment]
@bnoordhuis 
i tried also to add env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8 in my travis.yml file but nothing worked 
    -

**Comment by bnoordhuis** [comment]
It's not that. node-gyp is trying to download the node.js SDK over https but that doesn't work because of that bad TLS certificate.

If you're running on Travis CI, consult their documentation or open an issue with them to find out how outgoing HTTPS traffic is set up.

**Comment by Rachida-Djellal** [comment]
@bnoordhuis  this is what i got with node 20. and npm 10.x 
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ETIMEDOUT: request to https://registry.npmjs.org/iconv failed, reason: connect ETIMEDOUT 172.31.255.254:443
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.

> leveldown@0.10.6 install C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\leveldown
> node-gyp rebuild


gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.10.0/node-v20.10.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain
gyp ERR! stack at ClientRequest.<anonymous> (C:\Users\djellal.rachida\AppData\Roaming\npm\node_modules\node-gyp\node_modules\minipass-fetch\lib\index.js:130:14)
gyp ERR! stack at ClientRequest.emit (node:events:514:28)
gyp ERR! stack at _destroy (node:_http_client:875:13)
gyp ERR! stack at onSocketNT (node:_http_client:895:5)
gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\djellal.rachida\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\leveldown
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok

> iconv@2.1.4 install C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\iconv
> node-gyp rebuild


gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.10.0/node-v20.10.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain
gyp ERR! stack at ClientRequest.<anonymous> (C:\Users\djellal.rachida\AppData\Roaming\npm\node_modules\node-gyp\node_modules\minipass-fetch\lib\index.js:130:14)
gyp ERR! stack at ClientRequest.emit (node:events:514:28)
gyp ERR! stack at _destroy (node:_http_client:875:13)
gyp ERR! stack at onSocketNT (node:_http_client:895:5)
gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\djellal.rachida\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\iconv
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok
npm WARN miller-rabin@1.1.1 requires a peer of bn.js@^0.15.0 but none is installed. You must install peer dependencies yourself.
npm WARN The package request-json is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@0.10.6 (node_modules\leveldown):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: leveldown@0.10.6 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iconv@2.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\djellal.rachida\AppData\Roaming\npm-cache\_logs\2024-02-28T12_22_09_643Z-debug.log

C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails>npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'html-to-text@0.1.0',
npm WARN EBADENGINE   required: { node: '~0.8.0' },
npm WARN EBADENGINE   current: { node: 'v20.10.0', npm: '10.4.0' }
npm WARN EBADENGINE }
npm WARN deprecated request@2.34.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hoek@0.9.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hawk@1.0.0: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm ERR! code 1
npm ERR! path C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\iconv
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@20.10.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.1 found at "C:\Program Files\Python312\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v20.10.0/node-v20.10.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v20.10.0/node-v20.10.0-headers.tar.gz failed, reason: self-signed certificate in certificate chain
npm ERR! gyp ERR! stack at ClientRequest.<anonymous> (C:\Users\djellal.rachida\AppData\Roaming\npm\node_modules\npm\node_modules\minipass-fetch\lib\index.js:130:14)
npm ERR! gyp ERR! stack at ClientRequest.emit (node:events:514:28)
npm ERR! gyp ERR! stack at _destroy (node:_http_client:875:13)
npm ERR! gyp ERR! stack at onSocketNT (node:_http_client:895:5)
npm ERR! gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\djellal.rachida\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\djellal.rachida\Desktop\Nouveaudossier\emails\node_modules\iconv
npm ERR! gyp ERR! node -v v20.10.0
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\djellal.rachida\AppData\Local\npm-cache\_logs\2024-02-28T12_25_30_377Z-debug-0.log

**Comment by bnoordhuis** [comment]
Right, that's basically the same "self-signed certificate" error. I can't really help you with that, that's an issue with the http proxy you're trying to go through, presumably at that 172.31.255.254 address.
